sudo: false
language: cpp

compiler:
- gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
- make

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
