sudo: required

group: deprecated-2017Q2

language: cpp

services:
- docker

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make travis-pr; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make travis; fi'
