sudo: required

services:
  - docker

language: cpp

before_install:
- docker pull ubuntu:16.04
- docker run -d -p 127.0.0.1:80:4567 ubuntu:16.04 /bin/sh -c "bundle exec foreman start;"
- docker ps -a
- docker run ubuntu:16.04 /bin/sh -c "bundle exec rake test"

- git clone git://git.savannah.gnu.org/libjit.git /tmp/libjit/
- pushd /tmp/libjit/ && ./bootstrap && ./configure && make && sudo make install && popd
- sudo cp /usr/local/lib/libjit* /usr/lib/

script:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version
- make && make test
