sudo: required
dist: trusty
language: cpp

compiler:
- gcc

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - gcc-5.3
    - g++-5.3
    - texinfo

before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- git clone git://git.savannah.gnu.org/libjit.git /tmp/libjit/
- pushd /tmp/libjit/ && ./bootstrap && ./configure && make && sudo make install && popd
- sudo cp /usr/local/lib/libjit* /usr/lib/

script:
- make && make test
