sudo: required
dist: trusty

language: cpp

compiler:
- gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- cd /tmp/
- git clone git://git.savannah.gnu.org/libjit.git
- cd libjit/
- ./configure && make && make install

script:
- make

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
