name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt -y update
        sudo apt install -y --force-yes build-essential python wget libgmp-dev llvm-8-dev git libomp5 libomp-dev
        sudo ln -s /usr/lib/llvm-8/include/llvm /usr/include
        sudo ln -s /usr/lib/llvm-8/include/llvm-c /usr/include
        sudo ln -s /usr/lib/llvm-8/bin/llvm-config /usr/bin
    - name: Info
      run: |
        gcc -v
        gcc-8 -v
    - name: make test
      run: make test
